server:
  port: 7070
spring:
  application:
    name: server-01
eureka:
  client:
    service-url:
      defaultZone: http://eureka2:7071/eureka/,http://eureka3:7072/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka1
    #metadataMap:
     # instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
      
